function swapStyleSheet(e){document.getElementById("pagestyle").setAttribute("href",e)}$(document).ready(function(e){"use strict";e("body").on("click",".page-scroll",function(t){var s=e(this);e("html, body").stop().animate({scrollTop:e(s.attr("href")).offset().top},1500,"easeInOutExpo"),t.preventDefault()}),e("#main-slider").flexslider({animation:"fade",slideshowSpeed:3500,controlNav:!1,directionNav:!1});var t=e("#quote-slider");t.owlCarousel({navigation:!1,singleItem:!0,transitionStyle:"fade",autoPlay:3e3}),e(".shots-slider").slick({dots:!0,arrows:!1,speed:300,centerMode:!1,slidesToShow:4,slidesToScroll:1,responsive:[{breakpoint:1024,settings:{slidesToShow:3,slidesToScroll:1,infinite:!0,dots:!0}},{breakpoint:600,settings:{slidesToShow:3,slidesToScroll:1}},{breakpoint:480,settings:{slidesToShow:1,slidesToScroll:1}}]}),e("a[class^='prettyPhoto']").prettyPhoto({theme:"pp_default"}),jQuery(".corner").on("click",function(){e("#customizer").toggleClass("s-open")})}),$(".term-popup").on("click",function(){return $(".terms").addClass("terms-active"),$(".overlay-dark").addClass("active"),!1}),$(".t-close").on("click",function(){return $(".terms").removeClass("terms-active"),$(".overlay-dark").removeClass("active"),!1}),$(window).scroll(function(){var e=$(this).scrollTop();e>350?$("header").css("background","#000000").css("padding","0px 0px 13px"):$("header").css("background","transparent").css("padding","20px 0px 20px")}),$(function(){var e=new GMaps({el:"#map",lat:40.712784,lng:-74.005941,zoom:11,zoomControl:!1,scrollwheel:!1,controls:!1,zoomControlOpt:{style:"BIG",position:"TOP_LEFT"},panControl:!0,streetViewControl:!1,mapTypeControl:!1,overviewMapControl:!1,styles:[{featureType:"road",elementType:"labels",stylers:[{visibility:"simplified"},{lightness:20}]},{featureType:"administrative.land_parcel",elementType:"all",stylers:[{visibility:"off"}]},{featureType:"landscape.man_made",elementType:"all",stylers:[{visibility:"off"}]},{featureType:"transit",elementType:"all",stylers:[{visibility:"off"}]},{featureType:"road.local",elementType:"labels",stylers:[{visibility:"simplified"}]},{featureType:"road.local",elementType:"geometry",stylers:[{visibility:"simplified"}]},{featureType:"road.highway",elementType:"labels",stylers:[{visibility:"simplified"}]},{featureType:"poi",elementType:"labels",stylers:[{visibility:"off"}]},{featureType:"road.arterial",elementType:"labels",stylers:[{visibility:"off"}]},{featureType:"water",elementType:"all",stylers:[{hue:"#a1cdfc"},{saturation:30},{lightness:49}]},{featureType:"road.highway",elementType:"geometry",stylers:[{hue:"#f49935"}]},{featureType:"road.arterial",elementType:"geometry",stylers:[{hue:"#fad959"}]}]});e.addMarker({lat:40.712784,lng:-74.005941,icon:"images/mapicon.png"})});
$(function() {
var endDate = "August 20, 2015";
      $('.countdown.styled').countdown({
         date: endDate,
         render: function(data) {
           $(this.el).html("<div>" + this.leadingZeros(data.days, 2) + " <span>days</span></div><div>" + this.leadingZeros(data.hours, 2) + " <span>hrs</span></div><div>" + this.leadingZeros(data.min, 2) + " <span>min</span></div><div>" + this.leadingZeros(data.sec, 2) + " <span>sec</span></div>");
         }
      });
});
